#!/bin/bash

if [[ "$1" == "-s" ]]; then
  wallpapers=/home/joco/.wallpapers/pictures/
  folder=$(ls $wallpapers | shuf -n1)
  file=$(ls $wallpapers$folder | shuf -n1)
  fullPath=$wallpapers$folder/$file
  uri=file://$fullPath
  gsettings set org.gnome.desktop.background picture-uri $uri
  export WALLPAPER_PATH=$fullPath
elif [[ "$1" == "-r" ]]; then
  rm $WALLPAPER_PATH
  source /usr/local/bin/wallpaper -s
else
  echo "wrong command"
fi
