#!/bin/bash

if [[ "$1" == "-s" ]]; then
  wallpapers=/home/joco/.wallpapers/
  folder=$(ls $wallpapers | shuf -n1)
  file=$(ls $wallpapers$folder | shuf -n1)
  fullPath=$wallpapers$folder/$file
  xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP1/workspace0/last-image -s $fullPath
  xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorDP3/workspace0/last-image -s $fullPath || true &> /dev/null
  xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorHDMI1/workspace0/last-image -s $fullPath
  #xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorDP-1/workspace0/last-image -s $fullPath || true &> /dev/null
  #xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorDP2/workspace0/last-image -s $fullPath || true &> /dev/null
  #xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitorDP4/workspace0/last-image -s $fullPath || true &> /dev/null
elif [[ "$1" == "-r" ]]; then
  wallpaper_path=$(xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP1/workspace0/last-image)
  echo "Deleting $wallpaper_path"
  rm $wallpaper_path
  ~/.local/bin/wallpaper -s

else
  echo "wrong command"
fi
